<?php
namespace App\Models;
use Core\Model;

class ApplicationApiAccess extends Model
{
    function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->table('application_api_access');
    }
}